steps:
  # Build Backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-backend",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=ot2net",
        "./backend",
      ]

  # Build Frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-frontend",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAkOKV4NAS7UqNjZPo1WuKZ4L0wST6tXiQ",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=ot2net.firebaseapp.com",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=ot2net",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=ot2net.firebasestorage.app",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=21597837536",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_APP_ID=1:21597837536:web:9ecc63e8258854eb905885",
        "--build-arg",
        "NEXT_PUBLIC_API_URL=https://ot2net-backend-21597837536.us-central1.run.app",
        "./frontend",
      ]

  # Push Images
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-backend",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-frontend",
      ]

  # Deploy Backend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ot2net-backend"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-backend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"

  # Deploy Frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ot2net-frontend"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-frontend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-backend"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/ot2net-repo/ot2net-frontend"

options:
  logging: CLOUD_LOGGING_ONLY
